### ISSUE TITLE
The provided plugin com.jereksel.jailbreakk.MyComponentRegistrar is not compatible with this version of compiler

### ISSUE THREAD

**Issue by jereksel** [jereksel/jailbreakk#10]
```
 Error:Kotlin: [Internal Error] java.lang.IllegalStateException: The provided plugin com.jereksel.jailbreakk.MyComponentRegistrar is not compatible with this version of compiler
     at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli(KotlinCoreEnvironment.kt:606)
     at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.registerExtensionsFromPlugins(KotlinCoreEnvironment.kt:135)
     at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:175)
     at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:115)
     at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:422)
     at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:263)
     at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:152)
     at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:55)
     at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
     at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
     at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
     at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1479)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
     at sun.rmi.transport.Transport$1.run(Transport.java:200)
     at sun.rmi.transport.Transport$1.run(Transport.java:197)
     at java.security.AccessController.doPrivileged(Native Method)
     at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
     at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
     at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
     at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
     at java.security.AccessController.doPrivileged(Native Method)
     at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)
 Caused by: java.lang.AbstractMethodError
     at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli(KotlinCoreEnvironment.kt:598)
     ... 28 more
```

**Comment by jereksel** [comment]
Can be reproduced by setting `Build and run using` to `IntelliJ IDEA` in `Settings` -> `Build, Execution, Deployment` -> `Build Tools` -> `Gradle` -> `Runner`

I'm closing it, because it's non-default settings. I'll check it later ,when it will cause issues for user.
